language: python
sudo: false
deploy:
  provider: pypi
  user: arokem
  password:
    secure: JKKiOtcb6q69kf0ZIQaMkTroe60HhjrPe4/rw71govCR2w8PLAS/IxDyE5zmq9Au0FeJbDm2fJS9B1gsEDGJFX1Q/v9MrjyygZu06aThLh19QfkhxYFldPCynECp5oxrdMPBSRoJWEPe2SDpfVPw6Yw7rgtU0h2p4QqTpG2inGRsOOlcc84U/FjzmZ+mr2KaRr26ZhNUQf4Xec6Cg41QIOvSSNgZaPqmFz01P0IwcHuRPJt/T+suKXI/F9o6NSEDrFfU0KoOYz+7mT2r0ksSOI4DLNB0rXn4ZFwt++e8f+iZJreEelXsVoVupMoZWJX+y4Az9QBQ/QqEWMs18PwhrQup3a0XRFKqEEGUG3lW3POxIGMarqUj5QLVKClvFsIeWCQDbnX4x+OsUUSofK1b1JlecruGJUNX8/ZJRuDyx/CssmnBf5XR/CYn/UBA98CuMszy3xB6NjLRtWUPreosiQ5OFA0K3aZmhyE1Cjbvs/n59QNnx5rm1iwRizgkxsx6O7z8FV0V38J4Dfupv4b5B/KzkXNRajMnY7qD2/rZ67lXveCTgawGxBcLuTW+oyNzEs2ifKpoL/wryHjRAQ23iHnJJhfREshD2/lJXutVAx5+sXAtC5gW2b5eJuf9xFSH9fFoTK7T9kPsNSKNtKyYexut2+aYQ5nQ5hOEh1zGqxw=
  on:
    tags: true
    repo: popylar/popylar
env:
  global:
  - PIP_DEPS="coveralls pytest-cov flake8 doctr"
  - secure: "FNRIZW2v6gZupJshBsG/XlDoLszr/anGYLwWD2PMj/kecGfU9R4MnoE+p7cx4EQN+EItASd90cWu/dYpVLNQ13IjH09cYYzkOGSb4BhDo8I4aN3YmZ8l83aJfDuhrarAei5lvlqYoY5cXefEe1XAh6k2550MFCnB1ZSky4D+U9JMNZwmRUISylibKmBd0UNF6Ggma45a6t8UWlneL0PSXSddBo+O9IhDYYHrbjs45Gmk9/U8n90uZdK05ZZwceFPUzBZcC6GuZ0dL2vUmUx45i3LzQdWpoOTLtJx+qG3vP7POLuC6UVaFQLnbPkQCg8IbysSG2lpgIuP5iXXezAydU3HC2lu5dFHiQ0aBXkIN8r+6upRh+jz7x7MMviRKWdNxYeiEbs8EFc70WuoCQeRYkKgA+MZFrx5eAXwz5UANZh0fi+vUJrhisCUzKjxnf2A04oW3wu6t/0xiWFIIMVOF72n+QUohlN2uVIcC5zbMO82GZhkG+bDqDA7ZPTgi4Q2ICI9AFD3zTvmIKzazHdSfGbv5q5hyrPDz0LjLgHn9NgEnonZKUBchUr8HqPpW3LlV/sqk0Bm4r+udxTneGH2w4twXBbJFiSPMSB0H2/BIAEqAhWTMAcmhsu4xKdlW7KgIyzmXaX8OpPHCT32ADcWalldtc3duPA2Eq4Ac5/POM4="

python:
- '2.7'
- '3.5'
install:
- pip install $PIP_DEPS
- pip install -r requirements.txt
- python setup.py install
script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /docs/`
- py.test --pyargs popylar --cov-report term-missing --cov=popylar
- doctr deploy --deploy-repo popylar/popylar.github.io
after_success:
- coveralls
